// <auto-generated />
using LakePlay.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LakePlay.Migrations
{
    [DbContext(typeof(LakePlaySqliteContext))]
    [Migration("20240303222423_AddOptionFK")]
    partial class AddOptionFK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.27");

            modelBuilder.Entity("LakePlay.Data.TriviaQuestion", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AskedThisRound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Used")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b
                        .HasAnnotation("Cosmos:ContainerName", "Questions")
                        .HasAnnotation("Cosmos:PartitionKeyName", "Id");
                });

            modelBuilder.Entity("LakePlay.Data.TriviaQuestion", b =>
                {
                    b.OwnsMany("LakePlay.Data.TriviaQuestionOption", "ListOptions", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsAnswer")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("QuestionId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("TriviaQuestionId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("TriviaQuestionId");

                            b1.ToTable("TriviaQuestionOption");

                            b1.WithOwner()
                                .HasForeignKey("TriviaQuestionId");
                        });

                    b.Navigation("ListOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
